### PR TITLE
Update on Manta Ground Speed

### PR DESCRIPTION
**Pull request by HellDragon-HK**
1500 still feels a little faster than UT3 but it seems closer than 2000

### CODE REVIEW

**Comment by GreatEmerald** [comment]
The units for speed are not necessarily equivalent between games. Model size in UU differs between the games, and thus so will velocity measurements. It would be better to test in e.g. Torlan how long it takes to get from one known point to another and then compare.

**Comment by HellDragon-HK** [comment]
How would that work, Torlan in UT3 isn't the same size is it and it has extra paths :S

**Comment by GreatEmerald** [comment]
Or does it?.. I looked at the code, and `EyeHeight` is the same between the games. Usually that's a good indicator of the model size difference between games. Base (`UT`/`X`)`Pawn` also have the same `GroundSpeed` and `AirSpeed`. So maybe 1 UU is in fact the same size between the games after all... As for how to test it, I'm not entirely sure either.

I suppose we could go with the assumption that measurement units match precisely, and look into that once we get some evidence to the contrary. That would make life much easier. In that case, I'll accept this.

It's funny that ground speed for Manta matters, considering that it's not really on the ground, but that's how the tank works too, so it's not that surprising.

**Comment by HellDragon-HK** [comment]
I think what is going on is UT2004 has extra movement modifiers on vehicles such as I've noticed on wheeled vehicles with TransRatio which vastly effects speed but I haven't figured out how to fully work with it yet

**Pull request merged**
