### PR TITLE
Update UT3RaptorWeapon.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Got the plasma fire a lot closer to the gun barrels now

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Looks nice, but I'd like to have someone else confirm that this works as expected.

**Comment by Unre-Alex** [comment]
If this is for the drawscale 1.0 then the projectiles come straight from the gun barrels.

**Comment by GreatEmerald** [comment]
OK, thanks.

**Comment by HellDragon-HK** [comment]
Apparently it works on both drawscales without needing to change, then again I'm finding most weapons to be this way

**Pull request merged**
