### PR TITLE
Update UT3LeviathanDriverWeapon.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Slowed turret rotation closer to UT3 and re-aligned weapon fire for turret size increase

### CODE REVIEW

**Comment by GreatEmerald** [comment]
This requires an updated file for the meshes, doesn't it? Can you scale it up in code rather than doing it in the mesh?

**Comment by HellDragon-HK** [comment]
With the UT3 Drawscale these re-alignments will need to be re re-aligned I think first

**Comment by GreatEmerald** [comment]
So you're saying I shouldn't merge this yet, then?

**Comment by HellDragon-HK** [comment]
Well it works for what the current archive is so I'm not really sure, on my end it probably needs to be redone because the Levi is now radically different than the archive....so up to you I guess?

**Comment by GreatEmerald** [comment]
There's no point to changing it now if it will need to be changed again in the future, then. Update this request once you have the numbers for the UT3 DrawScale.

**Comment by HellDragon-HK** [comment]
Redone

**Pull request closed without merging**
