### PR TITLE
Update UT3Paladin.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Gives the Paladin it's compressed state like the Hellbender has

### CODE REVIEW

**Comment by GreatEmerald** [comment]
There's a conflict, please rebase on current master.

Also, it would be nice if someone else could test this as well.

**Comment by HellDragon-HK** [comment]
Wouldn't count as resolved unless I replaced the entire thing with everything in my class file, not sure if that's going to be an issue or not

**Comment by GreatEmerald** [comment]
No, this doesn't seem to work, because now it's proposing to revert all changes that 100GPing100 has done so far. Maybe try a new pull request.

**Comment by HellDragon-HK** [comment]
Figured as much ok then

**Pull request closed without merging**
