### PR TITLE
UT3 Hellbender Rear Turret Closer to UT3

### PR DESCRIPTION
**Pull request by HellDragon-HK**
In UT3 the Hellbender turrets don't turn instantly on PC and I've gotten consistent 85 damage to every vehicle I've shot with the rear turret

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Again this is just scaling damage against vehicles: http://greatemerald.xmpcommunity.com/uncodex/UT3-15/Source_utgamecontent/utdmgtype_hellbenderprimary.html

**Comment by HellDragon-HK** [comment]
So look at the LeviRocketTurret code you mean again?

**Comment by GreatEmerald** [comment]
Yeap, same principle.

**Comment by HellDragon-HK** [comment]
Is 120 the base damage because that's what I'm seeing in the UT3 code here http://greatemerald.xmpcommunity.com/uncodex/UT3-15/utgamecontent/utvweap_hellbenderprimary.html

so that is being scaled by the .85?

**Comment by GreatEmerald** [comment]
Correct, it's 120 damage and it gets scaled by 0.85 due to the damage type. This pull is fine now, but the damage scaling for vehicles still needs to be implemented.

**Comment by HellDragon-HK** [comment]
I thought I did add the scaling, what do you mean?

**Comment by GreatEmerald** [comment]
You need to add the DamageType .uc and set `MyDamageType` here.

**Comment by HellDragon-HK** [comment]
Wait you merged it before having the DamageType added?

**Comment by GreatEmerald** [comment]
Yes, as you can see. You didn't set `MyDamageType` so this doesn't cause a problem; it's simply just as inaccurate as it was before. Please open a new pull request with the `DamageType` added and applied.

**Pull request merged**
