### PR TITLE
Fix Hellbender Driver Death Message & Reupload Missing Dmg Types

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Death message closer to UT3 now, main reason of this was to upload the apparently missing Hellbender Combo class

### CODE REVIEW

**Comment by HellDragon-HK** [comment]
Can we confirm all the classes are there now,
DmgType_HellbenderCombo
DmgType_HellbenderLaser
DmgType_HellbenderRearGunBeam
UTHBShockBall (which is there by default right?)

**Comment by 100GPing100** [comment]
@HellDragon-HK Still missing `UT3DmgType_ScorpionBlades`.

**Comment by HellDragon-HK** [comment]
Ok I'll take care of it, another one I'm positive I uploaded....twice even....anything else?

**Comment by 100GPing100** [comment]
Yes, seems to be all; fixes #180 fixes #178

**Comment by GreatEmerald** [comment]
Looks fine, but `UT3DmgType_HellbenderCombo.uc` is missing the license.

**Comment by HellDragon-HK** [comment]
Oh not again....isn't that the EXACT same one that was the issue on last time?.....ugh

**Comment by GreatEmerald** [comment]
OK, thanks.

**Comment by HellDragon-HK** [comment]
Do we got everything that went missing after the purge restored now?

**Pull request merged**
