### PR TITLE
UT3 Paladin Combo Fire Sound Fix

### PR DESCRIPTION
**Pull request by HellDragon-HK**
According to the UT3 editor this explosion is the combo explosion sound and not a death explosion sound.

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Did you check whether that is also the case in-game?

**Comment by HellDragon-HK** [comment]
Yes I can hear this sound for the combo explosion in-game, and I checked the editor sound cue and it only has the 1 explosion used as death explosion, also the file name in the UT2004 package is named differently,
in UT2004 it's A_Vehicle_Paladin_Explode01 but in the UT3 editor it's A_Vehicle_Paladin_ComboExplosion01

**Comment by 100GPing100** [comment]
I'd like to mention it is likely that the sounds got mixed up. If I remember correctly when exporting them they'd come out with random names, so I'd have to match them with the editor and may have gotten the name wrong, and then proceding to get the sounds used wrong. If needed when I get some time I can look into UT3's source and confirm everything.

**Comment by HellDragon-HK** [comment]
I've been checking the editor and for the most part no other vehicles seem to be missing sounds except in-game I hear a loop with the Cicada when it's flying in UT3 that I'm not finding anywhere

**Comment by 100GPing100** [comment]
Got a fix made with correct sound names, should create pull request once I have some more free time.

**Comment by HellDragon-HK** [comment]
@100GPing100 Goliath is missing A_Vehicle_Goliath_EngineLoop, the uax does have a file of this name but to me seems like it's A_Vehicle_Goliath_EngineTreadLoop

**Comment by GreatEmerald** [comment]
Superseded.

For tweaks to other vehicles, move the comments to their respective pull requests.

**Pull request closed without merging**
