### PR TITLE
UT3 Leviathan Overall Improvements

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Not much here, it already handles like it does in UT3 I think, what has been changed includes...
-Speed
-Impact Damage
-Smoke & On Fire points (This is NOT in-line with UT3 as I feel it starts way too early, it's already on fire with at least 5100 health left in UT3, in UT2004 it's more toward 3000-2000 with these values which seems more reasonable)
-Exit Points
-How much it's thrown around
-Camera Views (There is an unlisted camera view somewhere that I can't edit yet which is getting out while moving drops you in the middle of the Levi just behind the front wheels)
-Headlights
-Headlight Projector
-Collision & Turret Size Update https://drive.google.com/open?id=1_2foPegkhCEcJ2hvyxMGEF7kD0fNqJSa
 (Driver Turret was too small and collision changes help Levi not bottom out)

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Looks good, but do use the UT3 values for fire. It was set like that on purpose for balancing reasons, looks like.

**Comment by HellDragon-HK** [comment]
Ah yeah I had a feeling you were going to say that, my only complaints are it doesn't make sense with that much health and it's deceptive for an attacker because anything on fire should be an easy target but that probably won't be

**Comment by HellDragon-HK** [comment]
Well there it is, damage phases changed.....but hear me out, what I think is it was set early for testing the effects and never changed, there are several things I've noticed about the Levi that support this theory, it has floating smoke exhaust that should have had a Z value but I'm guessing only has a quick guess X value, the driver turret looks like it was meant to have a light (or a scope look maybe) but doesn't, and the circles on the back of it resemble the Hellbender's reverse brake lights yet they never light up, it also has floating and kind of oddly placed smoke for it's damage phase, to me it seems like it was made game play ready but the visual special effects were still being worked on and never completed

**Comment by GreatEmerald** [comment]
Looks good. The damage phases could be adjusted sometime later. I still think it's a balancing thing, to make it respawn quicker at the base if someone (i.e. bot) leaves it empty.

**Comment by HellDragon-HK** [comment]
Trust me it respawns well before it can take much damage so I don't think so

**Pull request merged**
