### PR TITLE
Update UT3DmgType_ViperBolt.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
[UTDmgType_ViperBolt]
DeathString="`k's viper eviscerated `o with hot plasma."
FemaleSuicide="`o fired her gun prematurely."
MaleSuicide="`o fired his gun prematurely."

### CODE REVIEW

**Comment by GreatEmerald** [comment]
OK, thanks.

**Comment by HellDragon-HK** [comment]
Uh you're accepting this one even though suicide isn't the same message?


MaleSuicide="%o fried himself with his own plasma.";
FemaleSuicide="%o fried herself with her own plasma.";

[UTDmgType_ViperBolt]
DeathString="k's viper evisceratedo with hot plasma."
FemaleSuicide="o fired her gun prematurely." MaleSuicide="o fired his gun prematurely."

**Comment by GreatEmerald** [comment]
I'm not checking these myself; I expect that you have done it! Make another pull request for those, then.

**Comment by HellDragon-HK** [comment]
You've mentioned it on all the others and I was fixing those while you accepted this one

**Pull request merged**
