### PR TITLE
64-bit Compatible Textures

### PR DESCRIPTION
**Pull request by Unre-Alex**

### CODE REVIEW

**Comment by GreatEmerald** [comment]
What do you mean by that? If you remove all `[2]`, `[0]` and `(0)`s fromt he code, it should still work fine.

**Comment by HellDragon-HK** [comment]
Wouldn't that return it to not having a texture for the necris tech part, which in beta 4 it uses the Hellbender body texture there and looks fairly bad in my opinion.

**Comment by Unre-Alex** [comment]
Actually it works if they're removed, let me edit this then.

**Comment by GreatEmerald** [comment]
OK, thanks!

**Pull request merged**
