### PR TITLE
UT3 Raptor Plasma Fire Location Change

### PR DESCRIPTION
**Pull request by HellDragon-HK**
After a lot of tweaking this is currently the best I've been able to get the plasma to actually come from the gun barrels, I think all that is needed now is to move it downward but I haven't been able to figure out how and using the full (XYZ) doesn't seem to do anything.

### CODE REVIEW

**Comment by HellDragon-HK** [comment]
Actually after closer examination this might be better
    DualFireOffset = 37.0 //15.0

**Comment by GreatEmerald** [comment]
In that case, update the value.

**Comment by HellDragon-HK** [comment]
No problem, done and good morning

**Comment by GreatEmerald** [comment]
OK, looks good.

**Pull request merged**
