### PR TITLE
Update UT3LeviathanShieldEffectBlue.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Visual and size change to match UT3 a little more
NOTE: Don't forget Red and HitEffect variants as well

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Looks OK, but please also include the red variant to this pull request as well.

**Comment by HellDragon-HK** [comment]
Last time you deleted it as a duplicate so I didn't, so I am supposed to do both then?

**Comment by GreatEmerald** [comment]
Either works. It's more convenient for me if you close it yourself.

Anyway, the same question here: are you sure X here should be 0.7 and not 1.0?

**Comment by HellDragon-HK** [comment]
Yes, the shield needs to go about halfway across the Levi, and it does it as far as I can tell with this setting (with the visuals being different it's hard to tell), using the UT3 drawscale I rather doubt it's enough and 1.0 may not do it either.........wait I'm confusing X & Y aren't I....uh ok if this is how far out it is from the turret's front then no I can't really tell with the visuals but it looks close, it probably needs, actually if you accept the UT3 drawscale will need to be looked at again

**Comment by GreatEmerald** [comment]
Yea, so testing it with 1.0 on all three axes would be nice.

**Comment by HellDragon-HK** [comment]
I could use some help confirming the size, I think the values I've got are close though
I've been using this image as well as 2 others from different angles for reference to try and scale it
screenshot00001

**Comment by GreatEmerald** [comment]
Looking at the code:
http://greatemerald.xmpcommunity.com/uncodex/UT3-15/Source_utgamecontent/utpaladinshield.html
http://greatemerald.xmpcommunity.com/uncodex/UT3-15/Source_utgamecontent/utleviathanshield.html
...those are different meshes altogether.

**Comment by HellDragon-HK** [comment]
I guess this explains the scale difference then?
There doesn't appear to be a Leviathan usx file yet so what now?

**Pull request closed without merging**
