### PR TITLE
UT3 Raptor Plasma Closer to UT3 Blue

### PR DESCRIPTION
**Pull request by HellDragon-HK**
In UT3, a single Raptor plasma shot does mixed damage, 26 to a Hellbender, 48 to a Goliath (I don't understand this), 34 to a Scorpion and 32 to a Manta.....between 25 and 40 is what we should probably aim for and 28 or 30 is my opinion, maybe 32.

I believe 2000 is actually slower than what we see in UT3 but as that's what it has in the UT3 code I believe we should go with it.

### CODE REVIEW

**Comment by HellDragon-HK** [comment]
Alex helped me confirm 40 is the correct damage value we need

**Comment by GreatEmerald** [comment]
This makes no sense. The UT3 code says the damage is 20. If it says it's 20, it's 20. The only way it could be 40 is if there were two projectiles fired at the same time, but that doesn't seem likely at all. @Unre-Alex? Without a good explanation I cannot accept this.

Also, let's fold #42 into this one, no need for two issues on the same topic.

**Comment by Unre-Alex** [comment]
A single plasma shot takes 40 damage.

**Comment by HellDragon-HK** [comment]
Only if it's a precise hit on the body however which is what I don't understand and I'm not seeing any scaling in the code anywhere so I'm as lost as you guys are on it

**Comment by GreatEmerald** [comment]
Oh, now I see why:
http://greatemerald.xmpcommunity.com/uncodex/UT3-15/Source_utgamecontent/utproj_raptorbolt.html#9
It deals variable damage. This function needs to be implemented into the `DamageType`, then.

**Comment by HellDragon-HK** [comment]
you mean this?
function AttenuateDamage()
{
	if ( LifeSpan < 1.0 )
    {
		Damage = 0.75 * Default.Damage;
    }
	else
    {
		Damage = Default.Damage * FMin(2.0, Square(MaxSpeed)/VSizeSq(Velocity));
    }
}

**Comment by GreatEmerald** [comment]
Yes. Looking at the UT2004 source, though, there is no function `AttenuateDamage`, so this needs to be implemented into the projectile itself.

**Comment by HellDragon-HK** [comment]
PrimitiveComponent isn't compiling

**Comment by GreatEmerald** [comment]
Specifically, the function `Explode` from http://greatemerald.xmpcommunity.com/uncodex/UT2004/Source_onslaught/onsplasmaprojectile.html#44 needs to be adjusted to use that variable-damage function.

**Comment by HellDragon-HK** [comment]
I need some help here, I don't even understand what I'm reading here exactly

**Comment by GreatEmerald** [comment]
No no, it's the damage that needs to be changed. Something like this:
```UnrealScript
simulated function Explode(vector HitLocation, vector HitNormal)
{
    local float MyDamage;
    if ( LifeSpan < 1.0 )
    {
		MyDamage = 0.75 * Default.Damage;
    }
	else
    {
		MyDamage = Default.Damage * FMin(2.0, Square(MaxSpeed)/VSizeSq(Velocity));
    }

    if ( Role == ROLE_Authority )
        HurtRadius(MyDamage, DamageRadius, MyDamageType, MomentumTransfer, HitLocation );

    if ( EffectIsRelevant(Location,false) )
        Spawn(HitEffectClass,,, HitLocation + HitNormal*5, rotator(-HitNormal));

    PlaySound(Sound'WeaponSounds.BioRifle.BioRifleGoo2');

    Destroy();
}
```

I'm not sure if the FMin, Square and VSizeSq functions exist, but you can try this.

**Comment by HellDragon-HK** [comment]
C:\Unreal Anthology\UT2004\UT3Vehicles\Classes\UT3RaptorProjBlue.uc(113) : Error, Bad or missing expression after '/'

**Comment by GreatEmerald** [comment]
Hm, OK, that means there's no `VSizeSq()` in UT2004. Try replacing it with `Square(VSize())` like this:
```UnrealScript
MyDamage = Default.Damage * FMin(2.0, Square(MaxSpeed)/Square(VSize(Velocity)));
```

**Comment by HellDragon-HK** [comment]
Compiled but still only getting 20 damage on everything

**Comment by GreatEmerald** [comment]
Hm, and what if you change that line to:
```UnrealScript
MyDamage = Default.Damage * FMin(2.0, Square(MaxSpeed)/Square(Speed));
```
In any case you should have variable damage already, depending on how long the projectile has been out and what its speed is relative to the maximum speed (the longer it takes to hit after firing, the less damage it deals).

**Comment by HellDragon-HK** [comment]
And still only 20 on everything, vehicles shot include Manta, Scorpion, Hellbender, Goliath, and Raptor....all had only 20 damage from a close range single shot

**Comment by GreatEmerald** [comment]
That doesn't make sense to me. Update the pull request with the current code so that I could look for clues.

**Comment by HellDragon-HK** [comment]
Done, there you go

**Comment by GreatEmerald** [comment]
It looks fine, so why wouldn't it work? Keep in mind that the damage is going to be different from 21 only if the projectile hits something during its first 0.5 seconds of existence (yes, that is half a second, or 30 frames if you're playing at 60 FPS), at which point it should go from doing 56 to 28.

If you are sure it always deals 20 (where would that number even come from?), try debugging it by putting in a few logging statements right after the formula we changed and check the log file afterwards:
```UnrealScript
log(self@"Explode: Dealing damage:"@Default.Damage@"* FMin(2.0,"@Square(MaxSpeed)@"/"@Square(Speed)@")="@Default.Damage * FMin(2.0, Square(MaxSpeed)/Square(Speed)))
```

**Comment by HellDragon-HK** [comment]
Still only seeing 20 damage to vehicles in-game but if I read this log right that shouldn't be the case

criptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(2.0, 156250000.00 / 4000000.00 )= 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(2.0, 156250000.00 / 4000000.00 )= 40.00
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PlayHit:0047) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PlayHit:0061) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.DriverRadiusDamage:004B) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.DriverRadiusDamage:0061) Accessed None 'WeaponPawns'
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(2.0, 156250000.00 / 4000000.00 )= 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(2.0, 156250000.00 / 4000000.00 )= 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(2.0, 156250000.00 / 4000000.00 )= 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(2.0, 156250000.00 / 4000000.00 )= 40.00

**Comment by Unre-Alex** [comment]
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjBlue Explode: Dealing damage: 28.00 * FMin(2.0, 156250000.00 / 4000000.00 )= 56.00

**Comment by HellDragon-HK** [comment]
What's the actual damage to the vehicle though if you get in?

**Comment by Unre-Alex** [comment]
28

**Comment by HellDragon-HK** [comment]
Looks like what we originally said it was

-    Damage = 20.0 //GE: We're weaker! Hooray!
+    Damage = 28.0 //20.0 //GE: We're weaker! Hooray!

So it's not working for you either then and you're getting base 28 damage

**Comment by GreatEmerald** [comment]
Yeah, that makes no sense. The log says it deals double damage, that means it deals double damage. The only way that it would deal less is if the `DamageType` causes half damage to vehicles or so.

**Comment by HellDragon-HK** [comment]
I'm lost here, it shows in the log but is being ignored in-game as far as I can tell and we're only getting the base damage

**Comment by GreatEmerald** [comment]
You could also do another experiment: replace `FMin(2.0` with `FMin(20.0` and see how much damage that deals.

**Comment by Unre-Alex** [comment]
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjBlue Explode: Dealing damage: 28.00 * FMin(20.0, 156250000.00 / 4000000.00 )= 560.00

Still 28

**Comment by Unre-Alex** [comment]
But it destroys a turret that has 450 health with one shot...

**Comment by HellDragon-HK** [comment]
Still 20 on mine as well no matter the distance

ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(20.0, 156250000.00 / 4000000.00 )= 40.00

**Comment by Unre-Alex** [comment]
It works with turrets (takes around 50 damage) but not with the stock vehicles.

**Comment by GreatEmerald** [comment]
Wat. That still makes no sense. Vehicles do apply `VehicleDamageScaling` and due to the way projectile damage works they may take less if the vehicle is big compared to the projectile's damage radius, but this is ridiculous.

How about if you add:
```UnrealScript
MyDamageType = class'DamageType';
MyDamage = 500;
```
Right before `if ( Role == ROLE_Authority )` and check how much damage that does?

**Comment by HellDragon-HK** [comment]
Still 20, no change

Error: UT3Hellbender None (Function Onslaught.ONSVehicle.StaticPrecache:0068) Accessed null class context 'WeaponPawnClass'
Error: UT3Hellbender None (Function Onslaught.ONSVehicle.StaticPrecache:0068) Accessed null class context 'WeaponPawnClass'
Log: Spawning new actor for Viewport WindowsViewport
ScriptLog: New Player Ysarell id=c7f3dafd0ff85650dfd9f8666398d4b3
Error: UT3Hellbender None (Function Onslaught.ONSVehicle.StaticPrecache:0068) Accessed null class context 'WeaponPawnClass'
Error: UT3Hellbender None (Function Onslaught.ONSVehicle.StaticPrecache:0068) Accessed null class context 'WeaponPawnClass'
Log: Precaching: VCTF-UT3-Suspense.LevelInfo0
Error: UT3Hellbender None (Function Onslaught.ONSVehicle.StaticPrecache:0068) Accessed null class context 'WeaponPawnClass'
Error: UT3Hellbender None (Function Onslaught.ONSVehicle.StaticPrecache:0068) Accessed null class context 'WeaponPawnClass'
Log: Static mesh batches: 10936980 vertex bytes, 1245906 index bytes
Log: Allocating 16384 byte dynamic index buffer.
Log: Preprocessing:  Vertex stream total vertices: 542 Orig wedges: 542
Log: Finished precaching geometry in 0.481 seconds
Log: Finished precaching textures in 0.408 seconds
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:015A) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:0184) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:019B) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:01A3) Attempt to assign variable through None
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:01B5) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:01BD) Attempt to assign variable through None
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.SetTeamNum:005D) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.SetTeamNum:005D) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:015A) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:0184) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:019B) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:01A3) Attempt to assign variable through None
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:01B5) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PostNetBeginPlay:01BD) Attempt to assign variable through None
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.SetTeamNum:005D) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.SetTeamNum:005D) Accessed None 'WeaponPawns'
ScriptLog: START MATCH
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(20.0, 156250000.00 / 4000000.00 )= 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(20.0, 156250000.00 / 4000000.00 )= 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(20.0, 156250000.00 / 4000000.00 )= 40.00
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PlayHit:0047) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.PlayHit:0061) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.DriverRadiusDamage:004B) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.DriverRadiusDamage:0061) Accessed None 'WeaponPawns'
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(20.0, 156250000.00 / 4000000.00 )= 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 20.00 * FMin(20.0, 156250000.00 / 4000000.00 )= 40.00
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.FindEntryVehicle:0153) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.FindEntryVehicle:0169) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.FindEntryVehicle:018F) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.FindEntryVehicle:0153) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.FindEntryVehicle:0169) Accessed None 'WeaponPawns'
Warning: UT3Hellbender VCTF-UT3-Suspense.UT3Hellbender (Function Onslaught.ONSVehicle.FindEntryVehicle:018F) Accessed None 'WeaponPawns'

**Comment by GreatEmerald** [comment]
This is beyond weird... What if you try this function:
```UnrealScript
simulated function Explode(vector HitLocation, vector HitNormal)
{
    if ( LifeSpan < 1.0 )
		Damage = 0.75 * Default.Damage;
	else
		Damage = Default.Damage * FMin(2.0, Square(MaxSpeed)/VSizeSq(Velocity));

    log(self@"Explode: Dealing damage:"Damage@"when the default would be"@Default.Damage);
    Super.Explode(HitLocation, HitNormal);
}
```

**Comment by HellDragon-HK** [comment]
C:\Unreal Anthology\UT2004\UT3Vehicles\Classes\UT3RaptorProjRed.uc(109) : Error, Bad or missing expression after '/'
Compile aborted due to errors.
Failure - 1 error(s), 0 warning(s)

**Comment by GreatEmerald** [comment]
Oh right, that line should be `Damage = Default.Damage * FMin(2.0, Square(MaxSpeed)/Square(Speed));`

**Comment by HellDragon-HK** [comment]
C:\Unreal Anthology\UT2004\UT3Vehicles\Classes\UT3RaptorProjRed.uc(111) : Error, Call to 'log': Bad expression or missing ')'
Compile aborted due to errors.
Failure - 1 error(s), 0 warning(s)

**Comment by GreatEmerald** [comment]
You probably copied that statement before I edited the post. You can just recopy the whole thing.

**Comment by HellDragon-HK** [comment]
Nope still doing it 

C:\Unreal Anthology\UT2004\UT3Vehicles\Classes\UT3RaptorProjRed.uc(111) : Error, Call to 'log': Bad expression or missing ')'

with
````
simulated function Explode(vector HitLocation, vector HitNormal)
{
    if ( LifeSpan < 1.0 )
		Damage = 0.75 * Default.Damage;
	else
		Damage = Default.Damage * FMin(2.0, Square(MaxSpeed)/Square(Speed));

    log(self@"Explode: Dealing damage:"Damage@"when the default would be"@Default.Damage);
    Super.Explode(HitLocation, HitNormal);
}````

**Comment by GreatEmerald** [comment]
Yeap, that's not what I posted. Recopy it.

**Comment by HellDragon-HK** [comment]
Still just 20

ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 when the default would be 20.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 when the default would be 20.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 when the default would be 20.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 when the default would be 20.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 when the default would be 20.00

**Comment by GreatEmerald** [comment]
And then how would this work:
```UnrealScript
simulated function Explode(vector HitLocation, vector HitNormal)
{
    if ( LifeSpan < 1.0 )
		default.Damage = 0.75 * 20;
	else
		default.Damage = 20 * FMin(2.0, Square(MaxSpeed)/Square(Speed));

    log(self@"Explode: Dealing damage:"@Default.Damage);
    Super.Explode(HitLocation, HitNormal);
}
```

I'm guessing that somehow `default.Damage` is the only one that is getting picked up. If this one works, then also see if it works in a LAN game.

**Comment by HellDragon-HK** [comment]
In Instant Action all took 40 except Goliath which only took 20

ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 20.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: VCTF-UT3-Suspense.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00

In LAN 1 Manta took 32(?it had 168 left) and 1 Scorpion only took 20

ScriptLog: ONS-Dria.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 20.00
ScriptLog: ONS-Dria.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: ONS-Dria.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: ONS-Dria.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: ONS-Dria.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: ONS-Dria.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: ONS-Dria.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00
ScriptLog: ONS-Dria.UT3RaptorProjRed Explode: Dealing damage: 40.00 and the current damage value is 40.00

Thankfully I can grab this from the running server window because my script log has a whole gigantic mess of this...

Warning: MutUT3Hoverboards ONS-Dria.MutUT3Hoverboards (Function UT3Vehicles.MutUT3Hoverboards.Tick:001D) Accessed None 'Game'
Warning: OutPlayerController ONS-Dria.OutPlayerController (Function Outsider.OutPlayerController.RenderOverlays:001D) Accessed None 'Pawn'
Warning: OutPawn ONS-Dria.OutPawn (Function Outsider.OutPawn.TraceLaser:016F) Accessed None 'Owner'
Warning: OutCrosshair ONS-Dria.OutCrosshair (Function Outsider.OutCrosshair.SetTexture:0180) Accessed None 'HUD'
Warning: OutCrosshair ONS-Dria.OutCrosshair (Function Outsider.OutCrosshair.SetTexture:0248) Accessed None 'HUD'
Warning: OutCrosshair ONS-Dria.OutCrosshair (Function Outsider.OutCrosshair.SetTexture:0257) Accessed None 'HUD'
Warning: OutCrosshair ONS-Dria.OutCrosshair (Function Outsider.OutCrosshair.SetTexture:025F) Attempt to assign variable through None
Warning: OutPawn ONS-Dria.OutPawn (Function Outsider.OutPawn.TraceLaser:01B7) Accessed None 'Owner'
Warning: OutPawn ONS-Dria.OutPawn (Function Outsider.OutPawn.TraceLaser:01BF) Accessed None

**Comment by GreatEmerald** [comment]
Yea, the ones that took less are probably the ones you hit for the very first time. So then indeed it somehow only takes the default values into consideration... This should work in every case, then:

```UnrealScript
simulated function Explode(vector HitLocation, vector HitNormal)
{
    local float MyDamage;

    MyDamage = 20.0;

    if ( LifeSpan < 1.0 )
    {
        Damage = 0.75 * MyDamage;
        default.Damage = Damage;
    }
    else
    {
        Damage = MyDamage * FMin(2.0, Square(MaxSpeed)/Square(Speed));
        default.Damage = Damage;
    }

    Super.Explode(HitLocation, HitNormal);
}
```

However, this is not optimal because it changes the default damage of the projectile class every time a projectile explodes. It shouldn't cause visible issues but will probably cause extra traffic in online games.

**Comment by HellDragon-HK** [comment]
Goliath still only took 20 but everything else 40

**Comment by GreatEmerald** [comment]
@100GPing100 Any ideas about what could be causing this mysterious behaviour?

**Comment by HellDragon-HK** [comment]
Leaving this one because of the discussion, will close (or you can @GreatEmerald ) when no longer needed

**Comment by GreatEmerald** [comment]
Can close, just linking this with #173.

**Pull request closed without merging**
