### PR TITLE
Manta: Gun Barrel Movement

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Somewhere we lost the movement on the guns or perhaps I just missed adding it to the over all but this should restore it, it compiles and works in-game for me but it would be nice if someone could double check.

### CODE REVIEW

**Comment by GreatEmerald** [comment]
I'd appreciate a more descriptive function name than "Guns". For that matter, I'm not sure if these should even be in functions: anything that runs in `Tick` is extremely expensive because it's run on every frame, and calling functions probably adds some overhead.

**Comment by HellDragon-HK** [comment]
It's how 100GP1000 has it in Raptor, I just borrowed it

**Comment by GreatEmerald** [comment]
Yes, I can see that this is his code. I'm also saying that @100GPing100 should fix his Raptor code as well ;)

**Comment by HellDragon-HK** [comment]
Alright then what do you want it changed to assuming I can that is, anything above defaults is still touchy for me it feels like.

**Comment by GreatEmerald** [comment]
Replace `Guns();` with
```UnrealScript
SetBoneRotation('Barrel_rt', -DriverViewPitch, 0, 1);
SetBoneRotation('Barrel_lt', -DriverViewPitch, 0, 1);
```

**Comment by HellDragon-HK** [comment]
C:\Unreal Anthology\UT2004\UT3Vehicles\Classes\UT3Manta.uc(126) : Error, Call to 'SetBoneRotation': type mismatch in parameter 2

What do I need to do about Function Guns?

**Comment by GreatEmerald** [comment]
Right, it should be:
```UnrealScript
SetBoneRotation('Barrel_rt', rotator(-DriverViewPitch, 0, 0), 0, 1);
SetBoneRotation('Barrel_lt', rotator(-DriverViewPitch, 0, 0), 0, 1);
```

Remove it.

**Comment by HellDragon-HK** [comment]
Never seen this before

C:\Unreal Anthology\UT2004\UT3Vehicles\Classes\UT3Manta.uc(126) : Error, Can't convert 'IntProperty' to 'StructProperty'

**Comment by GreatEmerald** [comment]
How about this:
```UnrealScript
SetBoneRotation('Barrel_rt', rot(-DriverViewPitch, 0, 0), 0, 1);
SetBoneRotation('Barrel_lt', rot(-DriverViewPitch, 0, 0), 0, 1);
```

**Comment by HellDragon-HK** [comment]
C:\Unreal Anthology\UT2004\UT3Vehicles\Classes\UT3Manta.uc(126) : Error, Missing Pitch component of rotation
Compile aborted due to errors.

How is what I don't understand

**Comment by GreatEmerald** [comment]
Apparently `rot` is a literal and it only accepts literal values, not variables. Bleh. We have to settle for replacing `Guns()` with the entire contents of `Guns()` (except for the commented-out line), then.

**Comment by HellDragon-HK** [comment]
Which direction do you mean Function Guns into Delta Time or the other way around?

**Comment by GreatEmerald** [comment]
The former.

**Comment by HellDragon-HK** [comment]
C:\Unreal Anthology\UT2004\UT3Vehicles\Classes\UT3Manta.uc(126) : Error, 'Guns': Bad command or expression
Compile aborted due to errors.

````function Ailerons(float DeltaTime)
{
    local Rotator AileronsRotation;
    Super.Tick(DeltaTime);
    Guns();
    // 45° = 8192 RUU

    // 1000 = The velocity at wich the angle is of 45º
    AileronsRotation.Pitch = 8192 * (Velocity.Z / 1000) - Rotation.Pitch;

    if (AileronsRotation.Pitch > 8192)
        AileronsRotation.Pitch = 8192;
    else if (AileronsRotation.Pitch < -8192)
        AileronsRotation.Pitch = -8192;

    SetBoneRotation('Aileron_Rt', AileronsRotation, 0, 1);
    SetBoneRotation('Aileron_Lt', AileronsRotation, 0, 1);
    
    function Guns()
{
    local Rotator GunsRotation;

    GunsRotation.Pitch = -DriverViewPitch;
    //GunsRotation.Yaw = -DriverViewYaw;
    
    SetBoneRotation('Barrel_rt', GunsRotation, 0, 1);
    SetBoneRotation('Barrel_lt', GunsRotation, 0, 1);
}
}````

**Comment by GreatEmerald** [comment]
Uh. I said the contents of the function, not the function itself.

**Comment by HellDragon-HK** [comment]
Still not working

C:\Unreal Anthology\UT2004\UT3Vehicles\Classes\UT3Manta.uc(126) : Error, 'Guns': Bad command or expression
Compile aborted due to errors.

'function Ailerons(float DeltaTime)
{
    local Rotator AileronsRotation;
    Super.Tick(DeltaTime);
    Guns();
    // 45° = 8192 RUU

    // 1000 = The velocity at wich the angle is of 45º
    AileronsRotation.Pitch = 8192 * (Velocity.Z / 1000) - Rotation.Pitch;

    if (AileronsRotation.Pitch > 8192)
        AileronsRotation.Pitch = 8192;
    else if (AileronsRotation.Pitch < -8192)
        AileronsRotation.Pitch = -8192;

    SetBoneRotation('Aileron_Rt', AileronsRotation, 0, 1);
    SetBoneRotation('Aileron_Lt', AileronsRotation, 0, 1);
    

    local Rotator GunsRotation;
    GunsRotation.Pitch = -DriverViewPitch;
    //GunsRotation.Yaw = -DriverViewYaw;
    
    SetBoneRotation('Barrel_rt', GunsRotation, 0, 1);
    SetBoneRotation('Barrel_lt', GunsRotation, 0, 1);
'

**Comment by GreatEmerald** [comment]
You have a line `Guns();` which would call a nonexistent function now. Remove it.

**Comment by HellDragon-HK** [comment]
Oh ok, Guns is the bone name, that compiled and now just need to test it to see if it still works

**Comment by GreatEmerald** [comment]
No it's not, the bones are `Barrel_rt` and `Barrel_lt`.

**Comment by HellDragon-HK** [comment]
:S how does it compile then? Oh well if it works it works I guess...still going through your other messages at the moment before testing

**Comment by GreatEmerald** [comment]
The whole point of this was to remove all mention of `Guns`, which is a non-fitting function name that zeluisping came up with several years ago :P

**Comment by HellDragon-HK** [comment]
Something against it huh?  Well at any rate it did compile and it still works...still can't move left and right but it's better than nothing so far.

**Pull request closed without merging**
