### PR TITLE
UT3 Paladin Handling Tweaks to be Closer to UT3

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Some tweaks to handling to be closer to UT3

### CODE REVIEW

**Comment by HellDragon-HK** [comment]
Re-examining this so ignore it for now

**Comment by 100GPing100** [comment]
Tested and approved, trusting @HellDragon-HK on his testing.

**Comment by HellDragon-HK** [comment]
@100GPing100 I completely re-did this and e-mailed it to Alex, but I can put the new values here as well to try or can e-mail the uc to you

**Comment by 100GPing100** [comment]
@HellDragon-HK If you can e-mail it to me, that'd be nice!

**Comment by HellDragon-HK** [comment]
@100GPing100 I uh don't know your e-mail, can you put it up for a second so I can compose one?

**Comment by 100GPing100** [comment]
@HellDragon-HK It's in my bio! 😅

**Comment by HellDragon-HK** [comment]
Ok then hang a second while I attach them to the e-mail, is there anything you already have you don't need?

**Comment by 100GPing100** [comment]
@HellDragon-HK I only have the current `master` branch without any changes besides all of those you posted here as pull requests.

**Comment by HellDragon-HK** [comment]
Some of the requests have been edited recently though...safer to try and send it all just in case then

**Comment by 100GPing100** [comment]
@HellDragon-HK Yes, that works too!

**Comment by GreatEmerald** [comment]
Superseded.

**Pull request closed without merging**
