### PR TITLE
Update UT3LeviathanShield.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Shield visual and sound change to match UT3, ambientsound is not working though

### CODE REVIEW

**Comment by GreatEmerald** [comment]
The ambient should should work. Maybe try setting `AmbientSoundVolume=255`. Usually the ambient sounds have rather limited volume.

Does this require updates to binary files?

**Comment by HellDragon-HK** [comment]
I don't think so as I'm pretty sure the shield sounds were already in the Paladin uax so it's just a path change

**Comment by HellDragon-HK** [comment]
UT3Vehicles.UT3LeviathanShield: Unknown property in defaults:     AmbientSoundVolume=255

**Comment by GreatEmerald** [comment]
Oh, it's just `SoundVolume=255`.

**Pull request closed without merging**
