### PR TITLE
Manta Headlight Corona Examination

### PR DESCRIPTION
**Pull request by HellDragon-HK**
DO NOT MERGE THIS, it's the one you wanted to look at for the headlight corona not disappearing issue

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Ah yes, I see what causes the behaviour you were talking about. You have in `PostNetBeginPlay` a call to `Super.PostNetBeginPlay()`. This calls the `PostNetBeginPlay` function of the parent, `ONSVehicle`, which includes code to spawn an `ONSHeadlightCorona`! Which means that first an `ONSHeadlightCorona` gets spawned, then your code spawns a `UT3HeadlightCorona` *on top* of the `ONSHeadlightCorona`! And when the vehicle is destroyed, it destroys the `UT3HeadlightCorona`, but it loses track of the `ONSHeadlightCorona`, which is what you see.

The solution is to copy all `PostNetBeginPlay` code from http://greatemerald.xmpcommunity.com/uncodex/UT2004/Source_onslaught/onsvehicle.html#452 (yes, that's a lot of code), replace the first `Super.PostNetBeginPlay();` with `Super(SVehicle).PostNetBeginPlay();` (which calls the function in `SVehicle`, rather than `ONSVehicle`) and replace the reference to `ONSHeadlightCorona` with `UT3HeadlightCorona`.

**Comment by HellDragon-HK** [comment]
Including the spawn weapons part?

**Comment by GreatEmerald** [comment]
Yes, because there's no way to replace just one line, have to replace them all.

(This issue links to issue #110)

**Comment by HellDragon-HK** [comment]
Same issue, it works when getting in and out but when empty I'm seeing I guess the default corona always on from initial spawn, at least now it's disappearing with the vehicle corpse instead of just staying there endlessly.

**Comment by HellDragon-HK** [comment]
Ok with SVehicle that works but Manta has lost it's hover ability and just scrapes along the ground now but it hasn't lost it weapons, fire rate, or turning ability so that's a step up from what I got before.

**Comment by GreatEmerald** [comment]
Oh yes, that's because `ONSHoverCraft` also has code in `PostNetBeginPlay`. You also have to copy over all this code and put it at the top of the function: http://greatemerald.xmpcommunity.com/uncodex/UT2004/Source_onslaught/onshovercraft.html#114 (note: the "#114" in the URL is a reference to the line number).

**Comment by HellDragon-HK** [comment]
Well it can jump now but still doesn't hover

**Comment by GreatEmerald** [comment]
Put this up in the pull request so I could check.

**Comment by GreatEmerald** [comment]
Hm, what if you move `Super(SVehicle).PostNetBeginPlay();` right before `if (Role == ROLE_Authority)`?

**Comment by HellDragon-HK** [comment]
Hey that seems to have worked and here is what we get from all this hard work although placement seems off for some reason
shot00629
shot00630

**Comment by GreatEmerald** [comment]
Hm, good to know. However, doing all this for every single vehicle is going to be a nightmare.

Putting code to manually set the hue and saturation of headlights on each team change might be a more reasonable approach. For that matter, headlights are completely irrelevant to gameplay, so I'm pretty sure they don't even exist on servers, which should make it easy enough to change the hue by simply using a function like this:

```UnrealScript
simulated function TeamChanged()
{
    Super.TeamChanged();
    if (Level.NetMode != NM_DedicatedServer)
    {
        for(i = 0; i < HeadlightCorona.Length; i++)
        {
            HeadlightCorona[i].LightSaturation = 0;
            if (Team == 0)
                HeadlightCorona[i].LightHue = 0;
            if (Team == 1)
                HeadlightCorona[i].LightHue = 175;
        }
    }
}
```

**Comment by HellDragon-HK** [comment]
They show up on LAN game including projectors, so try that on a different vehicle then maybe because I don't want to undo all the work on the Manta just to try a new approach

**Comment by HellDragon-HK** [comment]
WOW! The red one looks evil with that, I'd say that solution might work, didn't test blowing it up or anything though.

shot00631
shot00633

**Comment by GreatEmerald** [comment]
Yeap, that function should be universal for every vehicle. If it works in LAN games, then that's good enough!

**Comment by HellDragon-HK** [comment]
I meant the default coronas and projectors, I'd need to check if that change works on LAN

**Comment by HellDragon-HK** [comment]
Yeah they show up on both LAN and joining a dedicated LAN

**Comment by GreatEmerald** [comment]
OK, great, then simply put that function in every single vehicle that has headlight coronas.

**Pull request closed without merging**
