### PR TITLE
UT3 Manta Gun Barrel Movement

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Add this in so the Manta's guns at least move up and down, anything else is going to have to be handled by you or 100Gping100

### CODE REVIEW

**Comment by HellDragon-HK** [comment]
Oops forgot something,

simulated function EmeraldTick(float DeltaTime)
{
Super.Tick(DeltaTime);
Guns();
if (!bHoldingDuck && DuckEffect!=None) {
    DuckEffect.Destroy();   
	}
}

**Comment by GreatEmerald** [comment]
Hah. You'd need to add those changes to the pull request.

Also, if there's a way to destroy the effect on an event rather than checking if it should be destroyed on each frame, that would be better. Not sure if there's a function for that, though.

**Comment by HellDragon-HK** [comment]
All I added was the Guns() the rest of that is your handiwork :P

**Comment by HellDragon-HK** [comment]
Included in overall, no longer needed

**Pull request closed without merging**
