### PR TITLE
Manta: Engine Pitch & Stop Time

### PR DESCRIPTION
**Pull request by 100GPing100**
Fixes issues from #9:

- No longer takes too long to come to a stop
- Reduced engine pitch

### CODE REVIEW

**Comment by HellDragon-HK** [comment]
I think the sound is closer now, still seems like it has a lower pitch in UT3 but speed sounds like it might be right, didn't make the uc edits to test stop time yet

**Comment by GreatEmerald** [comment]
Huh, how does that influence the stop time?

**Comment by 100GPing100** [comment]
`LongDamping` for forward/backward movement and `LatDamping` for sideways movement.

**Comment by HellDragon-HK** [comment]
Doesn't that slow down it's overall speed too though by slowing it's acceleration?

**Comment by 100GPing100** [comment]
I didn't feel any noticeable difference, neither here nor the Viper. The viper used to have a really high `LongDamping` (a value of `30`maybe) and it was still fast. From what I understand it should only take effect if we're not thrusting, but I may be mistaken. I'll try an insanely huge `LongDamping` value and come back with the results.

**Comment by HellDragon-HK** [comment]
With the Raptor & Cicada the LongDamping seemed to impact starting to move forward but I could've been wrong

**Comment by 100GPing100** [comment]
So changed to the most insane value that wouldn't make me die instantly or teleport everywhere (`2.0`) and I do not see any difference in the top movement speed, I can still get across `ONS-IslandHop` very quickly.

**Comment by HellDragon-HK** [comment]
So it doesn't affect when you first start moving though and how long it takes to reach max speed?

**Comment by 100GPing100** [comment]
Nope, just tested a value of `2.0` for both properties against a value of `0.1`, also for both, and it took the same time from the same starting point to the same end point (aka same time since it starts moving to reach the same end point in a straight line).

**Comment by HellDragon-HK** [comment]
Hm guess it functions differently for Raptor & Cicada then

**Comment by GreatEmerald** [comment]
Huh, good to know that this is the variable that affects it.

Unfortunately looks like this needs a rebase anyway as well.

**Comment by 100GPing100** [comment]
Hmm, this doesn't seem right? @GreatEmerald did I just fuck it up? xD

**Comment by 100GPing100** [comment]
Okay, here's what I'm gonna do. I'm going to delete my branch and create a new one, do the changes, commits, create new pull request. Right now this just got messy.

**Pull request closed without merging**
