### PR TITLE
Update UT3Scorpion.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
This restores the Scorpion's hatch animations for when it's sitting empty & in-use and also on eject automatically surprisingly.  Alex and I have both confirmed this works.

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Looks nice, but please also test online (local online match). I suspect that the `DriverLeft` function needs to be `simulated` or so to work online.

**Comment by HellDragon-HK** [comment]
I don't play online at all, but would a lan game work although you said for the host it's the same as a bot match so...?

**Comment by GreatEmerald** [comment]
Start a dedicated match and then join it with another instance of UT2004 on the same computer.

**Comment by HellDragon-HK** [comment]
Alright give me a second to try it

**Comment by HellDragon-HK** [comment]
Can't start a dedicated match, my PC is blocking it or something it opens the log window and then just vanishes soon after, this is happening across all installations modded and unmodded

**Comment by HellDragon-HK** [comment]
Ok finally got it, no idea what was wrong but it does appear to work including self destruct, when getting out the timing was off once but it still played the animation.

**Comment by GreatEmerald** [comment]
All right then.

**Pull request merged**
