### PR TITLE
Update UT3LeviathanTurret.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Updated for UT3 Drawscale, binary is required.....extra note I do believe the UT2004 characters fit in these seats way better than UT3 characters

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Same changes needed here for animations and `bAttachedDriver`.

**Comment by HellDragon-HK** [comment]
See Manta again please, none of those changes will compile

**Comment by GreatEmerald** [comment]
Now you know how to make them compile.

**Comment by HellDragon-HK** [comment]
Missed fixing this one sorry

**Comment by GreatEmerald** [comment]
OK, thanks.

**Pull request merged**
