### PR TITLE
Update UT3LeviathanTurretWeaponMinigun.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Scaling needed to be adjusted
New DmgType Here
https://drive.google.com/open?id=1MtROHsIV7qhAs6HazsrD5Qcqmp9IzGzT

### CODE REVIEW

**Comment by GreatEmerald** [comment]
You don't seem to be doing any scaling here, though?
As for the sound, can that be confirmed? Indeed mixups may have happened.
And include the .uc in the pull request too.

**Comment by HellDragon-HK** [comment]
the scaling is in the damage type and hold on I'll go double check the sound

**Comment by HellDragon-HK** [comment]
Yeah confirmed it's alt fire but more rapid in frequency than the normal handheld Stinger

**Comment by GreatEmerald** [comment]
Again, you destroyed the entirety of the `Classes/UT3LeviathanTurretWeaponMinigun.uc` file!

**Pull request closed without merging**
