### PR TITLE
Update UT3CicadaTurret.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Slight improvement for weapon fire position, can't seem to get WeaponFireOffset to do anything like Raptor was and guessing I need to adjust something else but what and where

### CODE REVIEW

**Comment by GreatEmerald** [comment]
It looks like `WeaponFireLocation` is what determines where it spawns.

**Comment by HellDragon-HK** [comment]
Ok I'll give it a shot (uh no pun intended), can you confirm which class that is before I start is it the Turret or TurretFire or other?

**Comment by GreatEmerald** [comment]
It's `ONSDualACSideGun`.

**Comment by HellDragon-HK** [comment]
Wait that's not right, I'm talking about the belly turret not the rockets

**Comment by GreatEmerald** [comment]
Oh. Well, it's still `WeaponFireLocation`, in `ONSDualACGatlingGun`.

Speaking of which, this is funny, here's how the beam skips past the body of the Cicada:
http://greatemerald.xmpcommunity.com/uncodex/UT2004/Source_onslaughtbp/onsdualacgatlinggun.html#20
This might be possible to use for the Leviathan shields for the Stinger and Beam turrets.

**Comment by HellDragon-HK** [comment]
Oh that's...not a default property, what do I need to copy there to avoid similar issues like with the Manta earlier?

**Comment by GreatEmerald** [comment]
Oh, it's calculated from this formula: http://greatemerald.xmpcommunity.com/uncodex/UT2004/Source_onslaught/onsweapon.html#887
So it's taking the location of `WeaponFireAttachmentBone` and applying `WeaponFireOffset` plus `DualFireOffset`.

**Comment by HellDragon-HK** [comment]
So copy & paste and start working with this?

````
simulated function CalcWeaponFire()
{
    local coords WeaponBoneCoords;
    local vector CurrentFireOffset;

    // Calculate fire offset in world space
    WeaponBoneCoords = GetBoneCoords(WeaponFireAttachmentBone);
    CurrentFireOffset = (WeaponFireOffset * vect(1,0,0)) + (DualFireOffset * vect(0,1,0));

    // Calculate rotation of the gun
    WeaponFireRotation = rotator(vector(CurrentAim) >> Rotation);

    // Calculate exact fire location
    WeaponFireLocation = WeaponBoneCoords.Origin + (CurrentFireOffset >> WeaponFireRotation);

    // Adjust fire rotation taking dual offset into account
    if (bDualIndependantTargeting)
        WeaponFireRotation = rotator(CurrentHitLocation - WeaponFireLocation);
}
````

**Comment by GreatEmerald** [comment]
No, just experiment with `WeaponFireOffset`.

**Pull request closed without merging**
