### PR TITLE
UT3 Scorpion Fire Damage Degrade Closer to UT3

### PR DESCRIPTION
**Pull request by HellDragon-HK**
In UT3 vehicles degrade from fire damage much quicker than UT2004, this value seems to be a close match

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Hm, what does this value change exactly?

**Comment by HellDragon-HK** [comment]
Fire destroys the vehicle quicker when it's on fire and empty which I didn't even know UT2004 had this feature until I looked

**Comment by HellDragon-HK** [comment]
I don't understand how this is conflicting

**Comment by HellDragon-HK** [comment]
Included in Overall, no longer needed

**Pull request closed without merging**
