### PR TITLE
UT3 Goliath Projectile Damage Update

### PR DESCRIPTION
**Pull request by HellDragon-HK**
Needed higher vehicle momentum scaling added (from 1.3 default UT2004 to 1.5 UT3)
New DmgType uc here
https://drive.google.com/open?id=1FaG3V_Gaod3OZ7kaFN_m8sbgSxwhpxhp

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Add it to your pull request, then.

**Comment by GreatEmerald** [comment]
Something went wrong here. You don't want to remove the projectile file, just add the damage type.

**Comment by HellDragon-HK** [comment]
I don't know any other way

**Comment by GreatEmerald** [comment]
The file `Classes/UT3GoliathProjectile.uc` is still missing!

**Pull request closed without merging**
