### PR TITLE
Cicada: Weapons Fire Location & Sound Update

### PR DESCRIPTION
**Pull request by HellDragon-HK**
DualFireOffset is the only thing that works, we still need to move it forward to actually be coming from the barrels but nothing works, WeaponOffset & WeaponFireLocation do nothing and I would think at a value of 800 or -800 I would have noticed something different but nothing so far.

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Are you sure you tested `WeaponFireOffset`? The only other possibility would be to change the `WeaponFireAttachmentBone` or to override the `CalcWeaponFire()` function.

**Comment by HellDragon-HK** [comment]
Yeap, this `WeaponFireOffset=(X=-800.0,Y=0.0,Z=0.0)` does nothing

**Comment by GreatEmerald** [comment]
It's not a vector, it's a float.

**Comment by HellDragon-HK** [comment]
Ok yeah that did something, I'll play around with it and see what I can get now thanks.

**Comment by HellDragon-HK** [comment]
Ok finally got it figured out I think but I'm unsure if the the TurretAltFire sound is working with current version, it was earlier so I'm not sure why it would change now.  @Unre-Alex could use some help confirming if it's working or not please, maybe I'm just getting badly randomized sounds which wouldn't be the first time.

**Comment by Unre-Alex** [comment]
You need to fix this.
```
TurretFireSound=sound'UT3A_Vehicle_Cicada.TurretFire.A_Vehicle_Cicada_TurretFire'

AltFireProjectileClass=class'UT3CicadaDecoy'
```

Turret's alt fire doesn't work if it uses the `UT3CicadaDecoyLaunch` class.

**Comment by HellDragon-HK** [comment]
What do you mean when you say doesn't work, it works in-game for me but may not have correct sound also this is the class in the stock UT2004 code in ONSDualACGattlingGun ````AltFireProjectileClass=class'ONSDecoy'````

I don't see DecoyLaunch anywhere as the AltFireProjectile class, where do you see that?

**Comment by Unre-Alex** [comment]
`AltFireProjectileClass` in `UT3CicadaTurret.uc`

It didn't work because of this:

`class UT3CicadaDecoyLaunch extends ONSDecoyLaunch;`

but then I got errors about this 2 lines:

```
    Emitters(0)=SpriteEmitter'SpriteEmitter16'
    AutoDestroy=true
```

now it works, but the altfire uses the stock sound.

**Comment by HellDragon-HK** [comment]
Sorry I'm still not understanding what went wrong here, ucc hasn't tossed me any errors on that :S  the sound issue I'm aware of, it was working so I'm not sure what changed.

**Comment by Unre-Alex** [comment]
change

`AltFireProjectileClass=class'UT3CicadaDecoy'` to `AltFireProjectileClass=class'UT3CicadaDecoyLaunch'`

and

`class UT3CicadaDecoyLaunch extends ONSDecoyLaunch;` to `class UT3CicadaDecoyLaunch extends ONSDecoy;
`

remove

```
    Emitters(0)=SpriteEmitter'SpriteEmitter16'

    AutoDestroy=true
```

**Comment by HellDragon-HK** [comment]
That doesn't make sense, according to http://greatemerald.xmpcommunity.com/uncodex/UT2004/onslaughtbp/onsdualacgatlinggun.html it shouldn't be ````AltFireProjectileClass=class'UT3CicadaDecoyLaunch'````

**Comment by Unre-Alex** [comment]
But you've created a class named like that.

**Comment by HellDragon-HK** [comment]
Yes, one is an emitter and the other a projectile

**Comment by Unre-Alex** [comment]
Where is UT3CicadaDecoy class then?

**Comment by HellDragon-HK** [comment]
It didn't get uploaded?

**Comment by Unre-Alex** [comment]
It's not in this pull request

**Comment by HellDragon-HK** [comment]
This isn't it? https://github.com/GreatEmerald/UT3Vehicles/pull/175/commits/a04d2d8235322ebfd9f81062fb240250dfa717c7#diff-03826f9005eafae518c5a6208f324a65

**Comment by Unre-Alex** [comment]
UT3CicadaDecoy.uc(42) : Warning, 'DecoyFlightSFXClass' obscures 'DecoyFlightSFXClass' defined in base class 'ONSDecoy'.
UT3CicadaDecoy.uc(43) : Warning, 'DecoyLaunchSFXClass' obscures 'DecoyLaunchSFXClass' defined in base class 'ONSDecoy'.
UT3CicadaDecoy.uc(44) : Warning, 'DecoyFlightSFX' obscures 'DecoyFlightSFX' defined in base class 'ONSDecoy'.
UT3CicadaDecoy.uc(45) : Warning, 'DecoyRange' obscures 'DecoyRange' defined in base class 'ONSDecoy'.
UT3CicadaDecoy.uc(47) : Warning, 'ProtectedTarget' obscures 'ProtectedTarget' defined in base class 'ONSDecoy'.

**Comment by HellDragon-HK** [comment]
Yeah I know about those but not sure what to do about them on my own...looks like I did forget to list them so good that you did

**Comment by Unre-Alex** [comment]
The altfire sound still uses the stock one.

**Comment by HellDragon-HK** [comment]
I know and I'm not sure why it did work now it doesn't, if you can help figure out why that would be great

**Pull request closed without merging**
