### PR TITLE
UT3 Hellfire SPMA Camera Size Fix

### PR DESCRIPTION
**Pull request by HellDragon-HK**
In UT3 the camera is fairly small, this probably isn't exact but it shouldn't be far off, also according to the sound files there should be this ambient sound but I haven't been able to get it to work so it seems to do nothing but I believe this is where it goes.

The explosion size is still large, I haven't found how to scale it down yet but in UT3 it's about the same size as the camera.

### CODE REVIEW

**Comment by GreatEmerald** [comment]
The explosion size is `DamageRadius`, if you want to adjust that.

**Comment by HellDragon-HK** [comment]
Can you point me to the class I need for that, there are so many for the SPMA I can't tell what is what, and I don't want to mess with the actual artillery fire shell radius

**Comment by GreatEmerald** [comment]
Oh, you mean the emitter, OK. Yea, you can't easily scale those I'm pretty sure.

**Comment by HellDragon-HK** [comment]
So leave that for later and call it a done for now, probably needs a new visual suited for it instead of trying to scale the old anyway right?

**Comment by GreatEmerald** [comment]
Exactly.

**Pull request merged**
