### PR TITLE
Update UT3Fury.uc

### PR DESCRIPTION
**Pull request by HellDragon-HK**

### CODE REVIEW

**Comment by GreatEmerald** [comment]
Woah, why is this plasma if the Fury doesn't fire plasma?

**Comment by HellDragon-HK** [comment]
It doesn't have a beam yet so calling it a sweeping beam isn't right and the Fury did have a bolt type damage

[UTDmgType_FuryBolt]
DeathString="`k's Fury filled `o with plasma."
FemaleSuicide="`o fried herself with her own plasma blast."
MaleSuicide="`o fried himself with his own plasma blast."


[UTDmgType_FuryBeam]
DeathString="`o was disintegrated by `k's beam."
MaleSuicide="`o disintegrated himself."
FemaleSuicide="`o disintegrated herself."

**Comment by GreatEmerald** [comment]
Eh, I don't see much reason to merge this as-is, it won't really help in the long run.

**Comment by HellDragon-HK** [comment]
Can't be used for setting up a template to work with later so the Fury is already different from Raptor and less work, otherwise won't we just have to re do this?

**Comment by GreatEmerald** [comment]
We'd have to redo this anyway, because none of the values will match the final ones.

**Pull request closed without merging**
